# Server Port Config
server.port=${PORT:8080}

# Static Resources Mapping
spring.web.resources.static-locations=classpath:/static/

# Custom Firebase Config Settings
firebase.credentials.path=${FIREBASE_CREDENTIALS_PATH:classpath:serviceAccountKey.json}
firebase.credentials.json=${FIREBASE_CREDENTIALS:}
allowed.origins=${ALLOWED_ORIGINS:http://localhost:8080,http://127.0.0.1:8080}

# Multipart Upload Constraints (Taha Jaffri Rule 8)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Console Logging Format & Levels (Taha Jaffri Rule 9)
logging.level.com.hemoconnect=INFO
logging.level.org.springframework.web=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Strict JSON Schema Deserialization
spring.jackson.deserialization.fail-on-unknown-properties=true

# Dynamic Client configurations
firebase.client.apiKey=AIzaSyBnkq_WzMDJOE1HkQ3j2sJMNaNq04aZtWQ
firebase.client.authDomain=hemoconnect-ak47.firebaseapp.com
firebase.client.projectId=hemoconnect-ak47
firebase.client.storageBucket=hemoconnect-ak47.firebasestorage.app
firebase.client.messagingSenderId=700247497128
firebase.client.appId=1:700247497128:web:41da05a5be83f32f16e59d
firebase.client.measurementId=G-H1QWBBX2FG
google.maps.apiKey=AIzaSyDHemoConnectDefaultAPIKey_ReplaceWithRealKey

